version: '3'
    
services:
  db:
    image: postgres:12.0-alpine
    environment:
      - POSTGRES_DB=djbase
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./container-data/postgresql:/var/lib/postgresql/data
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
volumes:
  container-data: